["directories"]
"input_path" = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/flask-api-activity/sample_file.csv"
"log_path" = "C:/Users/eserkai/OneDrive - Ericsson/Documents/Programming/Python/Training/flask-api-activity/logs"